server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/secureflow
    username: postgres
    password: 1234

  sql:
    init:
      mode: never

logging:
  level:
    org.springframework.r2dbc: DEBUG